# action name
name: 'onedrive-to-github-sync'

# action author
author: 'Benjamin Michaelis <gitben@michaelis.net>'

# action description
description: 'Syncs specified files from OneDrive to your local GitHub repo.'

# action input values
inputs:
  urls:
    description: 'Comma-seperated list of the share url of each file with ?download=1 appended'
    required: 'true:'
outputs:
  sum: # id of the output
    description: 'The sum of the inputs'

# action runner (golang:latest image)
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.urls }}

branding:
  icon: 'terminal'  
  color: 'blue'
